# Generated by Django 6.0.5 on 2026-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('ITR Filing', 'ITR Filing'), ('GST Filing', 'GST Filing'), ('TDS Filing', 'TDS Filing'), ('Bookkeeping', 'Bookkeeping'), ('Business Registration', 'Business Registration')], max_length=50)),
                ('message', models.TextField()),
                ('document', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
