# Generated by Django 6.0.5 on 2026-05-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('pan_card', models.FileField(upload_to='itr_documents/')),
                ('aadhaar_card', models.FileField(upload_to='itr_documents/')),
                ('form_16', models.FileField(upload_to='itr_documents/')),
                ('bank_statement', models.FileField(upload_to='itr_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
