# Generated by Django 6.0.5 on 2026-05-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_itrrequest_delete_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('bank_statement', models.FileField(upload_to='bookkeeping_documents/')),
                ('expense_records', models.FileField(upload_to='bookkeeping_documents/')),
                ('sales_records', models.FileField(upload_to='bookkeeping_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('gst_certificate', models.FileField(upload_to='gst_documents/')),
                ('sales_report', models.FileField(upload_to='gst_documents/')),
                ('purchase_report', models.FileField(upload_to='gst_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TDSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('pan_card', models.FileField(upload_to='tds_documents/')),
                ('tds_details', models.FileField(upload_to='tds_documents/')),
                ('salary_sheet', models.FileField(upload_to='tds_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
