# Generated by Django 6.0.5 on 2026-05-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_bookkeepingrequest_gstrequest_tdsrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itrrequest',
            name='form_16',
        ),
    ]
