# Generated by Django 6.0.5 on 2026-05-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_itrrequest_form_16'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bookkeeping_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.bookkeepingrequest')),
                ('gst_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.gstrequest')),
                ('itr_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.itrrequest')),
                ('tds_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.tdsrequest')),
            ],
        ),
    ]
