# Generated by Django 6.0.5 on 2026-05-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_additionaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='bookkeeping_additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bookkeeping_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.bookkeepingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='GSTAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='gst_additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gst_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.gstrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ITRAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='itr_additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('itr_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.itrrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TDSAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='tds_additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tds_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='services.tdsrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalDocument',
        ),
    ]
